name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set execute permissions for mvnw
        run: |
          chmod +x ./blog-backend/mvnw
          chmod +x ./text-validation-service/mvnw

      - name: Build Backend with Maven
        working-directory: ./blog-backend
        run: ./mvnw package -Dnative

      - name: Build Text-Validation Service with Maven
        working-directory: ./text-validation-service
        run: ./mvnw package -Dnative

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          docker build -f blog-backend/src/main/docker/Dockerfile.native -t ghcr.io/myster-blues-woman/blog-backend:latest .
          docker push ghcr.io/myster-blues-woman/blog-backend:latest

      - name: Build and Push Text-Validation Service
        run: |
          docker build -f text-validation-service/src/main/docker/Dockerfile.native -t ghcr.io/myster-blues-woman/text-validation-service:latest .
          docker push ghcr.io/myster-blues-woman/text-validation-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        run: |
          ssh user@your-server 'cd /path/to/your/project && docker-compose pull && docker-compose up -d'
